# Generated by Django 5.0.6 on 2024-06-06 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("CarDealership", "0001_initial"),
        ("Dealer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cardealership",
            name="dealership_cars",
            field=models.ManyToManyField(
                related_name="dealerships",
                through="Dealer.DealersSalesHistory",
                to="Dealer.dealercars",
                verbose_name="Машины",
            ),
        ),
        migrations.AddField(
            model_name="historicalcardealership",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
