# Generated by Django 5.0.6 on 2024-05-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarDealership', '0001_initial'),
        ('Dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealership',
            name='dealership_cars',
            field=models.ManyToManyField(related_name='dealerships', through='Dealer.DealersSalesHistory', to='Dealer.dealercars', verbose_name='Dealership cars to sale'),
        ),
    ]
