version: '3'

services:
  postgres_bd:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    networks:
      - custom

  django:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres_bd
    volumes:
      - django_data:/app
    networks:
      - custom

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - custom  
  
  celery:
    build: .
    container_name: celery
    command: celery -A web_dealership worker -l info
    env_file:
      - .env
    volumes:
      - django_data:/app
    depends_on:
      - django
      - redis
      - postgres_bd
    networks:
      - custom
    
  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A web_dealership.celery flower
    volumes:
      - django_data:/app
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"
    restart: on-failure

  celerybeat:
    build: .
    container_name: celerybeat
    command: celery -A web_dealership beat -l info
    env_file:
      - .env
    volumes:
      - django_data:/app
    depends_on:
      - celery
      - redis
      - postgres_bd
    networks:
      - custom

volumes:
  postgresdb_data:
  django_data:

networks:
  custom:
    driver: bridge