# Generated by Django 5.0.6 on 2024-06-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpurchasehistory",
            name="type_payment",
            field=models.CharField(
                choices=[
                    ("Наличные", "Наличные"),
                    ("Кредит", "Кредит"),
                    ("Банковская карта", "Банковская Карта"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomerpurchasehistory",
            name="type_payment",
            field=models.CharField(
                choices=[
                    ("Наличные", "Наличные"),
                    ("Кредит", "Кредит"),
                    ("Банковская карта", "Банковская Карта"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
